version: "3.9"
services:
  php:
    build: ./.docker/php
    volumes:
      - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./app:/var/www/html"
  nginx:
    image: nginx:alpine
    volumes:
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/html"
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - php
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
        - "3306:3306"
    environment:
      MYSQL_DATABASE: payapp
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - mysql-data:/var/lib/mysql
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 12345
volumes:
  mysql-data:
