api_post_users:
    path: /api/users
    methods: ['POST']
    controller: App\Payment\Infrastructure\Http\PostUsers
    defaults:
        _format: json
api_post_transactions:
    path: /api/transactions
    methods: ['POST']
    controller: App\Payment\Infrastructure\Http\PostTransactions
    defaults:
        _format: json
api_post_transfer:
    path: /api/transfer
    methods: ['POST']
    controller: App\Payment\Infrastructure\Http\PostTransactions
    defaults:
        _format: json
api_delete_transaction:
    path: /api/transactions/{id}
    methods: ['DELETE']
    controller: App\Payment\Infrastructure\Http\DeleteTransactions
    defaults:
        _format: json